FROM --platform=$BUILDPLATFORM python:3.9-alpine AS build
ARG TARGETPLATFORM
ARG BUILDPLATFORM


WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["waitress-serve", "--host", "0.0.0.0", "--port", "5000", "app:app"]